import { makeStyles } from '@material-ui/core/styles/';

export default makeStyles((theme) => ({
  wrapper: {
    display: 'flex',
    justifyContent: 'center',
  },
  tenNumber: {
    fontFamily: 'Cera Pro',
    fontStyle: 'italic',
    fontWeight: 'bold',
    fontSize: 30,
    lineHeight: '38px',
    textAlign: 'right',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: '#E2E7F1',
    textShadow: '2px 2px 0px rgba(0, 0, 0, 0.25)',
    width: 110,
    position: 'relative',
    top: -3,
    '@media (max-width: 500px)': {
      position: 'relative',
      paddingLeft: 7,
      top: -75,
      fontSize: 16,
      width: 0,
    },
  },
  textWrapper: {
    display: 'flex',
    flexDirection: 'column',
    transform: 'rotate(-9deg)',
  },
  topTitle: {
    marginBottom: -10,
    fontFamily: 'Cera Pro',
    fontStyle: 'italic',
    fontWeight: 500,
    fontSize: 30,
    lineHeight: '38px',
    textAlign: 'left',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: '#E2E7F1',
    textShadow: '2px 2px 0px rgba(0, 0, 0, 0.25)',
    '@media (max-width: 500px)': {
      fontSize: 16,
    },
  },
  mainTitle: {
    fontFamily: 'Cera Pro Bold',
    fontStyle: 'italic',
    fontWeight: 900,
    fontSize: 150,
    lineHeight: '135px',
    textAlign: 'center',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    color: '#D5E0F7',
    textShadow: '2px 2px 0px rgba(0, 0, 0, 0.25)',
    '@media (max-width: 500px)': {
      fontSize: 80,
      position: 'relative',
      top: -40,
    },
  },
  bottomTitle: {
    fontFamily: 'Cera Pro',
    fontStyle: 'italic',
    fontWeight: 500,
    fontSize: 30,
    lineHeight: '38px',
    textAlign: 'right',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: '#E2E7F1',
    textShadow: '2px 2px 0px rgba(0, 0, 0, 0.25)',
    width: 260,
    '@media (max-width: 500px)': {
      fontSize: 16,
      position: 'relative',
      top: -75,
      width: 139,
    },
  },
  contLabel: {
    display: 'flex',
  },
}));
